FROM cosmtrek/air:latest

# Install templ
RUN go install github.com/a-h/templ/cmd/templ@latest

# Set the working directory
WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Copy the air config file
COPY .air.toml .

# Command to run air
CMD ["air"]
